### ISSUE TITLE
ghost 1.5.0 can't use

### ISSUE THREAD

**Issue by hhuuuuuu** [MT-Libraries/ghost-oss-store#1]

**Comment by thonatos** [comment]
0.0, I will try later.

**Comment by unit2b** [comment]
I have a fork which works with Ghost 1.5.x, but may not compatible with previous versions.
There are also minor changes in config, see README.md

我做了一个可以支持 1.5.x 版本的 Fork，但是可能与之前的 Ghost 版本不兼容。
同时配置文件略有改动（有关 prefix) 部分，详见 README.md

https://github.com/unit2b/ghost-oss-store

**Comment by unit2b** [comment]
此外 https://github.com/MT-Libraries/ghost-oss-store/blob/master/index.js#L31 这个地方，如果用 path.join 的话，如果 prefix 是个完整的 URL，比如 "https://example.com/" 的话，似乎会生成畸形的 URL

**Comment by thonatos** [comment]
@unit2b 

T.T 之前写的时候只是图方便了~

1.5.x 虽然发了版，但是和之前1.0 beta 差别不是很大吧，要不要稳定了再改呢
（例如 gscan 的库现在还没更新依赖，会导致主题无法使用）

**Comment by thonatos** [comment]
合并了 @hxsf 的PR，应该可以了。
