### ISSUE TITLE
It cant work in ghost 1.21.2

### ISSUE THREAD

**Issue by damaome** [MT-Libraries/ghost-oss-store#10]
It cant work in ghost 1.21.2,c

**Comment by hxsf** [comment]
test in ghost 1.21.2, it works.

Maybe you use it behind a proxy like nginx? do you set the client_max_body_size in nginx's config?

**Comment by damaome** [comment]
But there is no "config.js" file     in ghost 1.21.2
how can i configure my oss-store
maybe config.[env].json?
Ghost-cli version 1.5.2
Ghost version 1.21.2
