### ISSUE TITLE
An error in README.md

### ISSUE THREAD

**Issue by hxsf** [MT-Libraries/ghost-oss-store#3]
https://github.com/MT-Libraries/ghost-oss-store/blob/aee714021408963c5b38027f693694aa3c66852e/README.md#L62

https://github.com/MT-Libraries/ghost-oss-store/blob/aee714021408963c5b38027f693694aa3c66852e/index.js#L95

**Comment by thonatos** [comment]
@hxsf 

 哪里错了~

**Comment by hxsf** [comment]
`prefix` can only be set as String, and it will no be formatted by `moment.js`

**Comment by thonatos** [comment]
Thanks, i will fix it.

according to [Using a custom storage module](https://docs.ghost.org/docs/using-a-custom-storage-module#section-known-custom-storage-adapters), the storage module has been changed a lot. 

so, PR is welcome . 😀

**Comment by hxsf** [comment]
https://github.com/MT-Libraries/ghost-oss-store/pull/2 Here it is.

**Comment by thonatos** [comment]
merged.

**Comment by hxsf** [comment]
^_^
