### ISSUE TITLE
/var/www/ghost/content/adapters/storage/oss-store/index.js:9

### ISSUE THREAD

**Issue by lixiang1994** [MT-Libraries/ghost-oss-store#4]
NAME: IncorrectUsageError
MESSAGE: We have detected an unknown error in your custom storage adapter.

<img width="1270" alt="qq20170909-231835 2x" src="https://user-images.githubusercontent.com/13112992/30241438-d546f6fe-95b5-11e7-95b7-e1ee28f5ae48.png">

Ghost-CLI version: 1.1.1
Ghost Version (at ~var/www/ghost): 1.8.4

**Comment by galenzh** [comment]
"region": "oss-cn-hangzhou" 这个字段默认配置的是杭州，你看一下你的bucket是不是其他区域的。参照这个改一下https://help.aliyun.com/document_detail/31837.html

**Comment by hxsf** [comment]
@lixiang1994 now try again?

**Comment by thonatos** [comment]
辛苦 @hxsf 了

**Comment by hxsf** [comment]
@thonatos will you publish to npm ?

**Comment by thonatos** [comment]
@hxsf done.
